version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "andresousar"
    assignees:
      - "andresousar"
    commit-message:
      prefix: "chore(api)"
      include: "scope"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "andresousar"
    assignees:
      - "andresousar"
    commit-message:
      prefix: "chore(web)"
      include: "scope"

  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "andresousar"
    assignees:
      - "andresousar"
    commit-message:
      prefix: "chore(root)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "andresousar"
    assignees:
      - "andresousar"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
