# GitHub Repository Settings for WhatsApp Manager Platform

# Repository name
name: whatsapp-manager-platform

# Description
description: "Plataforma profissional para gerenciamento centralizado de múltiplos números WhatsApp Business com RBAC, gestão de equipes e monitoramento de custos"

# Topics/Tags
topics:
  - whatsapp
  - business
  - management
  - platform
  - nestjs
  - react
  - typescript
  - rbac
  - multi-tenant
  - nodejs
  - postgresql
  - prisma
  - tailwindcss
  - shadcn-ui

# Repository settings
private: false
has_issues: true
has_projects: true
has_wiki: true
has_downloads: true
allow_squash_merge: true
allow_merge_commit: true
allow_rebase_merge: true
delete_branch_on_merge: true

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Backend Tests"
          - "Frontend Tests"
          - "Security Scan"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Backend Tests"
          - "Frontend Tests"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null

# Webhooks (configure manually in GitHub)
webhooks:
  - url: "https://your-domain.com/webhooks/github"
    content_type: "json"
    secret: "your-webhook-secret"
    events:
      - push
      - pull_request
      - release
